print('--------------------------------------------')
print('Tugas 1 SISOP Kelas-A')
print('--------------------------------------------')
print('Nama: Nada Salsabila')
print('21083010089')
print('--------------------------------------------')
print('notes:')
print('--------------------------------------------')
print('Halo dunia!')
print('Ini adalah skrip Bash pertamaku di Linux')
